Add note for custom images and arm-unknown-linux-gnueabihf.
cross-rs/cross pull request #1093
Opened 2022-10-24 16:58 UTC by Alexhuszagh

2022-10-24 17:00 UTC, Alexhuszagh commented
This produces the below warning message. This is needed because this has been repeatedly been an issue with people attempting to install such packages, and confused when we added them to a deny list by pinning all system installation candidates to a negative value (blocked).

![Screenshot_20221024_115911](https://user-images.githubusercontent.com/9440903/197583116-f9515f7c-c90e-4558-b4a5-9e57c138ea84.png)

2022-10-24 17:49 UTC, Emilgardis requested changes
I think

2022-10-24 17:49 UTC, Emilgardis commented on src/docker/shared.rs
> +            msg_info.warn("cannot install armhf system packages via apt for `arm-unknown-linux-gnueabihf`, since they are for ARMv7a targets but this target is ARMv6. installation of all packages for
I don't think this should be a "warning", instead maybe a "note" or "info" ?

2022-10-26 10:35 UTC, Emilgardis approved these changes
bors r+

2022-10-26 11:07 UTC, merged