Add C++ exception support to FreeBSD targets.
cross-rs/cross pull request #1132
Opened 2022-11-13 18:17 UTC by Alexhuszagh

2022-11-13 18:18 UTC, Alexhuszagh commented
So far I've only tested x86_64 so far: testing x86 right now.

2022-11-13 18:23 UTC, Alexhuszagh commented
bors try *freebsd

2022-11-13 18:34 UTC, Alexhuszagh commented
bors try-
bors try --target *freebsd

2022-11-13 18:39 UTC, Alexhuszagh commented
This passes the full test suite locally against the CMake re2 tests in #1112.

2022-11-17 15:38 UTC, Alexhuszagh commented
We can actually improve this IMO a lot, since we can just copy everything from `/lib` over (the entire contents are 10.6MB), which would guarantee improved future support, and then from there we can copy all the symlinks in `usr/lib`. Even though `libcrypto.so.11` exists in `/lib`, it won't conflict with the `openssl` packages which is installed in `/usr/local/lib`. And then do something like:

```bash
for lib in /lib/*.so.*; do
    base=$(basename "{lib}")
    link="${base}"
    # not strictly necessary since this will always work, but good fallback
    while [[ "${link}" == *.so.* ]]; then
        link="${link%.*}"
    done

    # just extra insurance that we won't overwrite it
    if [[ -n "${link}" ]] && [[ "${link}" != "${base}" ]]; then
        ln -s "${base}" "${destdir}/lib/${link}"
    fi
done
```

And then we have all our appropriate symlinks. We also need a few extra: specifically, `ln -s libthr.so.3 "${destdir}/lib/libpthread.so"`.

2022-11-19 02:40 UTC, Alexhuszagh commented
bors try --target *freebsd

This still passes the CMake tests.

2022-11-27 18:52 UTC, Alexhuszagh commented
Just a ping for a review on this.

2022-11-27 18:54 UTC, Emilgardis approved these changes

2022-11-27 18:54 UTC, Emilgardis commented
bors r+

2022-11-28 02:27 UTC, Alexhuszagh commented
My finest creation yet
bors try --target *freebsd

And now our changelog check is failing :/
https://github.com/cross-rs/cross/actions/runs/3561136338/jobs/5981770295#step:4:1344

```
  Error: Unable to locate a common ancestor between main and 31e5947b48c69fc911e015ef27f0d527ed214e5c
  Error: Process completed with exit code 1.
```

Except `31e5947b48c69fc911e015ef27f0d527ed214e5c` isn't part of the commit tree.

2022-11-28 05:40 UTC, Emilgardis commented
https://github.com/cross-rs/cross/commit/31e5947b48c69fc911e015ef27f0d527ed214e5c

does exists though, I think the synchronize event misfired for some reason, triggered the ci again with a new event and it works now

2022-11-28 06:28 UTC, Emilgardis requested changes

2022-11-28 06:28 UTC, Emilgardis commented on docker/freebsd.sh
> +            echo -e "\e[1;33mWarning:\e[0m Mirror ${home} does not seem to work." 1>&2
```suggestion
            echo -e "\e[1;33mwarning:\e[0m Mirror ${home} does not seem to work." 1>&2
```

2022-11-28 06:28 UTC, Emilgardis commented on docker/freebsd.sh
> +    echo "Could not find a working FreeBSD mirror." 1>&2
```suggestion
    echo "error: Could not find a working FreeBSD mirror." 1>&2
```

2022-11-28 06:28 UTC, Emilgardis commented on docker/freebsd.sh
> +        echo "Could not find a candidate release for FreeBSD ${BSD_MAJOR}." 1>&2
```suggestion
        echo "error: Could not find a candidate release for FreeBSD ${BSD_MAJOR}." 1>&2
```

2022-11-28 13:49 UTC, Alexhuszagh commented
bors r=Emilgardis

2022-11-28 14:36 UTC, merged

2022-11-28 15:28 UTC, Alexhuszagh commented
It looks lijke we have a spurious error with the packages hosting site, but if this becomes an issue, I'll try to setup a mirror:

```
#20 4.262 + curl --retry 3 -sSfL https://pkg.freebsd.org/FreeBSD:12:amd64/quarterly/packagesite.txz -O
(6) Could not resolve host: pkg.freebsd.org
#20 25.32 curl: (6) Could not resolve host: pkg.freebsd.org
#20 37.34 curl: (6) Could not resolve host: pkg.freebsd.org
#20 51.38 curl: (6) Could not resolve host: pkg.freebsd.org
```