Bugfix: custom image tag can't end with neither a `-` nor `.`
cross-rs/cross pull request #1171
Opened 2022-12-08 11:55 UTC by growse

The original bug fix solved the problem of a image name ending in a single `-` character (which docker doesn't permit). However, docker also doesn't permit names ending in a `.`, so we need to handle that case too.

Also, removing just the last char is insufficient, as names may end up ending with multiple consecutive `-` or `.` characters, so we need to loop until they're all gone.

2022-12-08 13:39 UTC, Alexhuszagh requested changes
Very minor change for idiomatic Rust expressions, otherwise, looks good to me.

2022-12-08 16:03 UTC, Alexhuszagh commented
lgtm, just squash the commit history and I'll approve and merge it.

2023-01-05 07:38 UTC, Emilgardis approved these changes
Thanks!

bors r=Alexhuszagh,emilgardis

2023-01-05 08:54 UTC, Emilgardis commented
bors retry

2023-01-05 09:06 UTC, merged