docker: Add gfortran support
cross-rs/cross pull request #1458
Opened 2024-03-13 15:03 UTC by Dirreke

Add gfortran support for all docker except target of `*-none*` and `*-andriod*`.

Close #1457

2024-03-13 16:35 UTC, Emilgardis requested changes
looks good so far!

One issue with this, it doesn't install it for the case where we use `Dockerfile.native`, which is used when doing `cargo build-docker-image x86_64-unknown-linux-gnu --platform="linux/x86_64=x86_64-unknown-linux-gnu"` (or just `cargo build-docker-image x86_64-unknown-linux-gnu`)

Easiest way to fix that would be to just install gfortran in linux-image.sh, perhaps add a install here: https://github.com/cross-rs/cross/blob/085092ca01d6ac9f5a0b612d9e68bcdf1e50f7ee/docker/linux-image.sh#L420-L423

2024-03-13 16:35 UTC, Emilgardis commented on docker/dragonfly.sh
> +        --enable-languages=c,c++,,fortran \
```suggestion
        --enable-languages=c,c++,fortran \
```

2024-03-13 16:35 UTC, Emilgardis commented on docker/Dockerfile.powerpc64-unknown-linux-gnu
> +    gfrotran-powerpc64-linux-gnu \
```suggestion
    gfortran-powerpc64-linux-gnu \
```

2024-03-13 16:35 UTC, Emilgardis commented on docker/Dockerfile.mips-unknown-linux-gnu
> +    gfrotran-mips-linux-gnu \
```suggestion
    gfortran-mips-linux-gnu \
```

2024-03-13 16:35 UTC, Emilgardis commented
/ci try

2024-03-14 19:43 UTC, Emilgardis commented
/ci try

lets try again!

2024-03-23 02:12 UTC, Emilgardis commented
/ci try

2024-04-03 14:02 UTC, Dirreke commented
Is any idea about why [aarch64-linux-android](https://github.com/cross-rs/cross/actions/runs/8398717508/job/23003943207?pr=1458#logs) failed? It seems that it just need more time to finish the build.

2024-05-01 06:27 UTC, Dirreke commented
As [libc/3618](https://github.com/rust-lang/libc/pull/3618) has beed merged, let's try again @Emilgardis

2024-05-01 06:32 UTC, Emilgardis commented
/ci try

2024-05-01 07:39 UTC, Dirreke commented
It doesn't seem to be my fault. Should we try again? Or could we merge it?

2024-05-01 08:19 UTC, Emilgardis approved these changes
Lets merge this! Thank you!

2024-05-01 09:33 UTC, Dirreke commented
timeout again. Could we adjust the settings of action?

2024-05-01 10:24 UTC, Emilgardis commented
it should already be maxed out: https://github.com/cross-rs/cross/actions/runs/8907127039/workflow#L188 however I rememember something about it not applying like you would expect. Lets just try again

2024-05-01 11:26 UTC, merged