feat: add loongarch64-unknown-linux-gnu image
cross-rs/cross pull request #1465
Opened 2024-04-02 13:54 UTC by heiher

This PR introduces a basic build-only image for the `loongarch64-unknown-linux-gnu` target. The Debian port for LoongArch is currently underway, and we anticipate further developments in the near future.

Close #1404

2024-04-02 14:13 UTC, Emilgardis requested changes
looks good! I'd like the ng config file to be changed a bit though

2024-04-02 14:13 UTC, Emilgardis commented on docker/crosstool-config/loongarch64-unknown-linux-gnu.config
how was this generated? I'd rather have a smaller ng file, see [`cargo xtask configure-crosstool`](https://github.com/cross-rs/cross/blob/main/xtask/src/crosstool.rs), a bunch of these flags are not needed

2024-04-02 15:10 UTC, heiher commented on docker/crosstool-config/loongarch64-unknown-linux-gnu.config
Thanks! I've replaced some lines to make it easier to generate with `cargo xtask configure-crosstool`. If [crosstool-ng.sh](https://github.com/cross-rs/cross/blob/main/docker/crosstool-ng.sh) can support `defconfig`, the config file can be further reduced, just like in the rust project: [loongarch64-unknown-linux-gnu.defconfig](https://github.com/rust-lang/rust/blob/master/src/ci/docker/host-x86_64/dist-loongarch64-linux/loongarch64-unknown-linux-gnu.defconfig)

2024-04-02 15:41 UTC, Emilgardis commented on docker/crosstool-config/loongarch64-unknown-linux-gnu.config
Thanks!

> just like in the rust project

Yep, it definitely is something I want to have. It was introduced in rust-lang just when we started using crosstool-ng like rust-lang does and we never got to it.

2024-04-02 15:44 UTC, Emilgardis approved these changes
Thank you!

2024-04-02 16:25 UTC, merged

2024-08-28 21:12 UTC, mcandre commented
Amazing! When will the next cross version release?