Add qemu-user runners for loongarch64-linux-gnu
cross-rs/cross pull request #1466
Opened 2024-04-03 06:51 UTC by heiher

Even though the Debian/LoongArch port is still in progress, qemu-user is now available. This PR adds qemu-user runners for the `loongarch64-unknown-linux-gnu` target.

2024-04-03 07:00 UTC, Emilgardis commented
/ci try

2024-04-03 12:41 UTC, heiher commented
/ci try

2024-04-03 12:45 UTC, Emilgardis commented
/ci try

2024-04-03 13:58 UTC, Emilgardis requested changes
LGTM!

This change updates qemu for a lot of the targets, can you edit the commit message and title of the pr to reflect this. Ideally we should also update the readme with correct qemu versions, but that can be done later, it just takes some time to do the inventory

2024-04-03 14:14 UTC, heiher commented
> LGTM!
> 
> This change updates qemu for a lot of the targets, can you edit the commit message and title of the pr to reflect this. Ideally we should also update the readme with correct qemu versions, but that can be done later, it just takes some time to do the inventory

Thanks! Done.

(PS: This PR enables editing by maintainers. Feel free to make direct edits if you have better ideas. :smiley:

2024-04-04 05:43 UTC, Emilgardis commented on .changes/1466.json
> +    "description": "add qemu-user runners for loongarch64-linux-gnu",
This should be updated too

2024-04-04 10:19 UTC, Emilgardis approved these changes
Thank you!

2024-04-04 10:29 UTC, merged