Draft: Updated Docker image to Ubuntu-24.04 and Cargo dependencies
cross-rs/cross pull request #1580
Opened 2024-10-26 22:43 UTC by JanDiederich

There were attempts to update to Ubuntu 22 (#973), and then Ubuntu 24, but that seems to have stopped? Also the dependencies were outdated.

So I updated them, but I can't get it running. I tried to build the Docker image for ARM64 Linux, but it stops in an endless loop. The command line is `cargo build-docker-image aarch64_be-unknown-linux-gnu-cross --tag local`.
In `crosstool-ng.sh`:
```bash
    download() {
        # timeout is a command, not a built-in, so it won't
        # work with any bash functions: must call a command.
        timeout "${timeout}" \
            su "${username}" -c \
            "STOP=${step} CT_DEBUG_CT_SAVE_STEPS=1 ${crosstooldir}/bin/ct-ng build.${nproc}"
    }

    while silence_stdout download; [ $? -eq 124 ]; do
        # Indicates a timeout, repeat the command.
        sleep "${sleep}"
    done
```

Please, can anyone give me a hint how to fix that?

2024-10-27 08:18 UTC, Emilgardis commented
/ci try

2024-10-30 20:32 UTC, JanDiederich commented
Looking at the died down predecessor #973 I don't expect any help soon. On the other hand: This project is super famous and used by many, many people.
If you added a donate button I would donate a little bit. Maybe others too? Maybe even if the single tips are small, they sum up to something bigger and were enough of a motivation?

2024-10-30 21:45 UTC, Emilgardis commented
Thank you for the consideration, I'd rather get help with contributions like this rather than money <3 I don't think a way to donate would motivate me, but maybe it could motivate other invited maintainers? I have no clue :3

I'll look into the issue you reported, but try setting `VERBOSE=1` in the dockerfile to see if there's an error message, we're silencing stdout

2024-12-01 16:19 UTC, JanDiederich commented
`VERBOSE=1` didn't help, but I could get it a bit further in the compiling, so I get now the following error in my build process when I use the updated "cross":

```
LC_ALL="C" PATH="/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin" VSLANG="1033" "cc" "-Wl,--version-script=/tmp/rustceDa4y3/list" "-Wl,--no-undefined-version" "/tmp/rustceDa4y3/symbols.o" "/target/aarch64-unknown-linux-gnu/release/deps/zune_jpeg-83beae640ba15514.zune_jpeg.21f0ac8659d152a4-cgu.0.rcgu.o" "/target/aarch64-unknown-linux-gnu/release/deps/zune_jpeg-83beae640ba15514.zune_jpeg.21f0ac8659d152a4-cgu.1.rcgu.o" "/tar ...
```

Note how it is filled with `nightly-x86_64-unknown-linux-gnu` instead of `...aarch64...`, how can I fix that?

2024-12-01 21:33 UTC, Emilgardis commented
`nightly-x86_64-unknown-linux-gnu` is the correct toolchain to use though, the target may be aarch64, but the toolchain runs on x86_64

2024-12-01 23:25 UTC, petehayes102 commented
I managed to get all the way to testing the targets before bombing: https://github.com/petehayes102/cross/actions/runs/12102553312.

You can see my commits on top of your original one: https://github.com/petehayes102/cross/commits/trying/. I messed up this branch so it says its miles ahead of `main`, though that's just a dodgy rebase!

2025-03-30 17:25 UTC, JanDiederich commented
@petehayes102:
I got sidetracked with other projects, but I continued trying to get it to work. So I continued based on your work. Big thanks for that.
So far I changed only my own code. I compile in `cross` with: `cargo build-docker-image aarch64_be-unknown-linux-gnu-cross --tag local`. My `Dockerfile` uses:
```Dockerfile
FROM ghcr.io/cross-rs/aarch64_be-unknown-linux-gnu-cross:local
ARG DEBIAN_FRONTEND=noninteractive
RUN dpkg --add-architecture arm64
RUN apt-get install -y \
  gcc-aarch64-linux-gnu \
  g++-aarch64-linux-gnu \
  binutils-aarch64-linux-gnu \
  libfontconfig1-dev
```
I had to configure all my libraries which used some CPU specific SIMD code in their defaults to use other libraries / "vendor" feature, etc.. Then, when I cross-compile my project, I get a lot of this messages: `Relocations in generic ELF (EM: 183)`. Which means that the compiler or linker used is for the wrong architecture.

Any ideas how to solve that?

2025-03-30 18:05 UTC, Emilgardis commented
I'd guess gcc-aarch64-linux-gnu is not correct for be

2025-03-30 21:15 UTC, JanDiederich commented
> I'd guess gcc-aarch64-linux-gnu is not correct for be

Ups. Yes, you were right, I was mixing be and le. Fixed that. Now it's `cargo build-docker-image aarch64-unknown-linux-gnu --tag local` on the `cross` side.
And in my project I tried this `Dockerfile`:
```Dockerfile
FROM ghcr.io/cross-rs/aarch64-unknown-linux-gnu:local
ARG DEBIAN_FRONTEND=noninteractive
RUN dpkg --add-architecture arm64
RUN echo -e "Types: deb\n\
URIs: http://ports.ubuntu.com/ubuntu-ports\n\
Suites: noble\n\
Components: main universe\n\
Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg\n\
Enabled: yes" >> "/etc/apt/sources.list.d/ubuntu.sources"

RUN apt-get update -o APT::Architecture="arm64" -o APT::Architectures="arm64"; exit 0
RUN apt-get install -y \
  gcc-aarch64-linux-gnu \
  g++-aarch64-linux-gnu \
  binutils-aarch64-linux-gnu \
  libfontconfig1-dev
```
But I always get the same error lines at the end:
```
note: /usr/lib/gcc-cross/aarch64-linux-gnu/13/../../../../aarch64-linux-gnu/bin/ld: skipping incompatible /usr/lib/x86_64-linux-gnu/libfreetype.so when searching for -lfreetype
          /usr/lib/gcc-cross/aarch64-linux-gnu/13/../../../../aarch64-linux-gnu/bin/ld: skipping incompatible /usr/lib/x86_64-linux-gnu/libfreetype.a when searching for -lfreetype
          /usr/lib/gcc-cross/aarch64-linux-gnu/13/../../../../aarch64-linux-gnu/bin/ld: cannot find -lfreetype: No such file or directory
          /usr/lib/gcc-cross/aarch64-linux-gnu/13/../../../../aarch64-linux-gnu/bin/ld: skipping incompatible /usr/lib/x86_64-linux-gnu/libfreetype.so when searching for -lfreetype
          /usr/lib/gcc-cross/aarch64-linux-gnu/13/../../../../aarch64-linux-gnu/bin/ld: skipping incompatible /usr/lib/x86_64-linux-gnu/libgcc_s.so.1 when searching for libgcc_s.so.1
          collect2: error: ld returned 1 exit status
```

2025-03-30 22:27 UTC, Emilgardis commented
don't you need `libfontconfig1-dev:arm64` ?

2025-03-31 22:06 UTC, JanDiederich commented
> don't you need `libfontconfig1-dev:arm64` ?
> also, why install gcc etc again?

Failed attempts to solve dependency problems. When I append ":arm64" the installation failed.
When adding arm64 I can get only something like this:
```
#9 0.487 The following packages have unmet dependencies:
#9 0.523  adduser : Depends: passwd but it is not going to be installed
#9 0.523  autoconf : Depends: perl (> 5.005) but it is not going to be installed
#9 0.523             Depends: m4 (>= 1.4.13) but it is not going to be installed
#9 0.523             Depends: debianutils (>= 1.8) but it is not going to be installed
#9 0.523  bsdextrautils : Depends: libsmartcols1 (>= 2.39.1) but it is not going to be installed
#9 0.523  g++-13-aarch64-linux-gnu:amd64 : Depends: libstdc++-13-dev-arm64-cross:amd64 (>= 13) but it is not installable
   ... and so on and on ...
```
For me it seems it runs like this:
* Install "package:arm64". Solve dependency "y".
* Try to find "y"... **Without ":arm64"**, therefore trying to install amd64.
* And then fails because "amd64" is of course incompatible to "arm64".

To solve this I tried this in the `Dockerfile`:
```Dockerfile
# Disable all non-arm64 sources
RUN sed -i -e 's/Enabled: yes/Enabled: no/g' /etc/apt/sources.list.d/ubuntu.sources

# Add arm64 sources as the only valid sources
RUN echo -e "Types: deb\n\
URIs: http://ports.ubuntu.com/ubuntu-ports\n\
Suites: noble\n\
Components: main universe\n\
Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg\n\
Enabled: yes" >> "/etc/apt/sources.list.d/ubuntu.sources"
```

It doesn't seem to help at all.

2025-04-02 20:06 UTC, JanDiederich commented
@Emilgardis Regarding the package installation problems, do you have any idea how this problem happens?
I get this:
```
debianutils : Conflicts: debianutils:amd64
debianutils:amd64 : Conflicts: debianutils but 5.17build1 is to be installed
```
when I try to install the `debianutils:arm64` package.
Should it be ":amd64", while the other packages stay ":arm64"?
I'm confused?!

2025-06-10 21:17 UTC, JanDiederich commented
@Emilgardis Is there a way I can persuade someone to solve this? Maybe with a donation after all?

2025-08-07 22:40 UTC, JanDiederich commented
@Emilgardis Any update?

2025-08-15 15:31 UTC, JanDiederich commented
I updated some crates and Rust and now "xargo" isn't compiling anymore, which is for a long time now in maintenance only mode. "Xargo" doesn't seem to easy to fix too. This seems like a never-ending story.

2025-08-15 15:38 UTC, Emilgardis commented
Xargo can be dropped, its not relevant anymore

2025-08-15 15:40 UTC, Emilgardis commented
Also sorry for not seeing your earlier comments! I have completely missed them. Ill take a look at what you've said and give a response if needed

2025-08-15 21:13 UTC, Emilgardis commented
Not sure how to solve the issues you're seeing, also not sure why it happens :/

2025-08-16 01:37 UTC, JanDiederich commented
> Xargo can be dropped, its not relevant anymore

Big thanks. I commented it out everywhere, that already helped a lot. I could get it to compile with the latest Rust and the latest packages.

It _seems_ smoothed out, but I still struggle with the part where I _use_ it. I can't get it to compile my project due to basic conflicts. Where I need the `debianutils` in the arm64 version, but the system refuses to install them because they conflict with the already installed `amd64` version. I tried removing the essentials packages `dash` and `bash`, so I could remove `debianutils:amd64` and then reinstall the `arm64` versions, but that doesn't work, because after I removed the amd64 packages, the image was so broken, no installation of anything was possible anymore.

2025-08-17 00:52 UTC, JanDiederich commented
I think (but aren't sure) my PR now works for the most part, and the problems I have are personal package installation problems, which have nothing to do with my PR branch.
So I rebased my PR and fixed the CI chain. The only thing I find irritating was Owo-Colors, which got its Stdin removed in its Stream, so I commented OwoColors-Stdin everywhere out. Because, if I understand it correctly, Owo-Colors is used to colorize the terminal output, why should it have StdIn colorization anyway?

2025-08-17 09:36 UTC, Emilgardis commented
/ci try

2025-08-17 09:43 UTC, Emilgardis commented
#1611 is fine, the issue was how to resolve the old dependency without introducing multiple versions of crates.



> [..] if I understand it correctly, Owo-Colors is used to colorize the terminal output, why should it have StdIn colorization anyway?

I think that's right, the impl can be removed :)

2025-08-19 21:20 UTC, JanDiederich commented
> #1611 is fine, the issue was how to resolve the old dependency without introducing multiple versions of crates.
> 
> > [..] if I understand it correctly, Owo-Colors is used to colorize the terminal output, why should it have StdIn colorization anyway?
> 
> I think that's right, the impl can be removed :)

So should I just remove the commented out code completely?

# Anyway: I cracked it! :smile:!
The problem is with Ubuntu 24 and how it treats missing packages for requested architectures (`apt-get install`).
If you explicitly specify `blaBla:arm64` and it searches in `http://archive.ubuntu.com/ubuntu` and `http://ports.ubuntu.com/ubuntu-ports` and it finds it _only_ in `...-ports`, it will tell you: There is no package and it can't download _anything_!

So, you must add the architectures to each source (in ubuntu.sources), like this:
```
URIs: http://ports.ubuntu.com/ubuntu-ports
Architectures: arm64
...
URIs: http://archive.ubuntu.com/ubuntu
Architectures: amd64 i386
```
It saves you also time, because it won't look in the wrong places where the packages don't exist anyway.

So, instead of adding this to all my Dockerfiles, I added this to the end of each of cross's aarch64 Dockerfile:
```
COPY ubuntu.sources /etc/apt/sources.list.d/
```
This is a prepared `ubuntu.sources` with the arm64 architecture added to "ports". I have no knowledge of all the other 50 (?) other architectures this project provides and how the Debian sources configuration for them looks like, so I limited this to aarch64 / arm64.

2025-08-19 23:52 UTC, petehayes102 commented
Well done @JanDiederich!! Thank you for persisting with this. Great job!

2025-08-20 13:45 UTC, Emilgardis commented
I'm sorry, I should have realized this earlier.. That's essentially what I do here: https://github.com/cross-rs/cross/issues/751#issuecomment-1776759292 with `sed 's/^deb http/deb [arch=arm64] http/' -i '/etc/apt/sources.list'`

2025-08-20 21:28 UTC, JanDiederich commented
> I'm sorry, I should have realized this earlier.. That's essentially what I do here: [#751 (comment)](https://github.com/cross-rs/cross/issues/751#issuecomment-1776759292) with `sed 's/^deb http/deb [arch=arm64] http/' -i '/etc/apt/sources.list'`

Maybe, but that's outdated now. With Ubuntu 24 the `sources.list` got deprecated, replaced by `ubuntu.sources`, with the [new syntax](https://repolib.readthedocs.io/en/latest/deb822-format.html). So I still think copying a template is a good idea. Or some much more sophisticated `sed`!?

## Compilation and running
After a long time I got my first cross-compilation running again, under my always up-to-date Ubuntu 24 and installed it on my always up-to-date Raspberry Pi OS and... It didn't work. This was the first time I had a glibc version conflict, I solved it by manually compiling and installing the specific glibc version 2.39 on my Raspberry Pi - which supports out-of-the-box only glibc 2.36.

Like this:
### Compilation and installation
```shell
sudo apt install build-essential wget tar
sudo apt install gawk bison

wget http://ftp.gnu.org/gnu/libc/glibc-2.39.tar.gz
tar -xvzf glibc-2.39.tar.gz
cd glibc-2.39
mkdir build
cd build

../configure --prefix=/opt/glibc-2.39
make -j$(nproc)
sudo make install
```
### Run program
```shell
/opt/glibc-2.39/lib/ld-linux-aarch64.so.1 --library-path /opt/glibc-2.39/lib:/usr/lib/aarch64-linux-gnu ./your_program
```
I write this as a help for others, and also because I saw a `max_glibc_version()` function in the `target_info.sh` script, maybe that's a point where a manipulation should be done and explicitly limit this to a specific glibc version (optionally of course)?

2025-08-21 19:19 UTC, JanDiederich commented
@Emilgardis As I wrote myself, I neither know all supported architectures, nor am I a Linux professional. But I think most people here are also no _general_ experts in this fields. But they know _their_ stuff and have an idea how to get it working.

So my suggestion is: You merge this into an "_edge_" branch, release that, and let the people Pull-Request this into a polished final version.

2025-08-22 05:10 UTC, Emilgardis commented
I dont think an edge branch qpproach is necessary, if the image doesnt build then the previous build will be used.

I'll have a closer look at this PR, probably submit some patches myself and then merge. Thank you!

/ci try

2025-08-22 05:23 UTC, Emilgardis commented
Ill reiterate here also why I'm considering merging this pr now before releasing 0.3.0. The ubuntu version we're currently using on main is not maintained now, and trying to patch the tools and repos to make it work is a bigger pain for maintaining the project, therefore the approach of updating the base version of ubuntu is much more attractive to further the development and hopefully then finally push 0.3.0 of cross once all images we want are compliant

2025-08-29 21:38 UTC, JanDiederich commented
> Ill reiterate here also why I'm considering merging this pr now before releasing 0.3.0. The ubuntu version we're currently using on main is not maintained now, and trying to patch the tools and repos to make it work is a bigger pain for maintaining the project, therefore the approach of updating the base version of ubuntu is much more attractive to further the development and hopefully then finally push 0.3.0 of cross once all images we want are compliant

Well, I'm all for it.

2025-09-06 00:45 UTC, JanDiederich commented
> I'm *considering* merging this pr now...

Well, do you have still some open questions I may answer?

2025-09-06 16:29 UTC, daywalker90 commented
Am i understanding this PR correctly that it would raise the glibc version for every cross compiled binary to that of ubuntu 24.04? That would kind of defeat the whole purpose of using `cross` for me. When i'm cross compiling for my users i just want them to have a binary they can execute without them having to compile or install anything. For that i want `cross` to use the oldest reasonable glibc version possible.

2025-09-07 09:55 UTC, Emilgardis requested changes

2025-09-07 09:55 UTC, Emilgardis commented on docker/cross-toolchains
this needs to be restored

2025-09-07 09:55 UTC, Emilgardis commented on docker/ubuntu.sources
> +Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg
```suggestion
Types: deb deb-src
URIs: http://ports.ubuntu.com/ubuntu-ports
Suites: noble noble-updates noble-backports noble-security
Architectures: arm64 armhf
Components: main restricted universe multiverse
Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg
```

2025-09-07 09:55 UTC, Emilgardis commented on src/bin/commands/containers.rs
> +    let is_tty = /* io::Stdin::is_atty() && */ io::Stdout::is_atty() && io::Stderr::is_atty();
remove this comment

2025-09-07 09:55 UTC, Emilgardis commented on src/docker/local.rs
> +    /* io::Stdin::is_atty() && */
remove comment

2025-09-07 09:55 UTC, Emilgardis commented on src/shell.rs
> +// }
can remove this too :)

2025-09-07 09:55 UTC, Emilgardis commented on README.md
> +and its compilation is now problematic.
```suggestion
### Xargo

"Xargo" is no longer supported since its maintenance was stopped a long time ago,
most of the functionality is available when using `build-std`.
```

2025-09-07 10:01 UTC, Emilgardis commented
> Am i understanding this PR correctly that it would raise the glibc version for every cross compiled binary to that of ubuntu 24.04? That would kind of defeat the whole purpose of using `cross` for me. When i'm cross compiling for my users i just want them to have a binary they can execute without them having to compile or install anything. For that i want `cross` to use the oldest reasonable glibc version possible.

Yes, that's correct @daywalker90 . I've been thinking about switching entirely to a crosstool-ng setup for all targets, which would make it possible for us to just set the glibc (and other deps) versions ourselves. But that's not how it is today.

But! minimal glibc is not a goal of `cross-rs`, I can recommend to you [`cargo-zigbuild`](https://github.com/rust-cross/cargo-zigbuild/) however which has it as a goal. We do support it from config also with [`.zig`](https://github.com/cross-rs/cross/blob/main/docs/config_file.md#targettargetzig)

2025-09-07 16:18 UTC, JanDiederich commented
@Emilgardis I pushed all requested fixes, I hope it's all to your liking.

There's only one thing: While I fixed almost all CI test errors, there came one thing up which doesn't stop the project from compiling or working, but "CI / cargo-deny" is constantly unhappy with. Now there are some windows-... packages which exist in 2 versions in the `Cargo.lock`. Deleting any of the "Duplicates" is pointless, the first thing `cargo build` does, is adding all removed dependencies back into the `Cargo.lock` file.

2025-09-07 18:05 UTC, Emilgardis commented on src/lib.rs
> -    clippy::string_to_string,
this lint is still relevant for 1.89.0, it's deprecated in 1.90.0, replaced with `clippy:implicit_clone`

2025-09-08 20:07 UTC, JanDiederich commented on src/lib.rs
> -    clippy::string_to_string,
Sure, I have no strong opinion about that and I could remove it, but on the other hand: The stable 1.90.0 release will be in 10 days, [2025-09-18](https://releases.rs/docs/1.90.0/), and till then I assume this branch won't be released anyway?! And I would want to update to the latest Rust version before this branch gets released, and we're maybe stuck with that Rust version for a very long time.

So, should I really undo this?

2025-09-09 06:56 UTC, Emilgardis commented on src/lib.rs
> -    clippy::string_to_string,
alright, leave it be, I'll just keep this in my head for now :D

2025-09-09 07:20 UTC, Emilgardis commented
/ci try

2025-09-09 12:31 UTC, Emilgardis commented
/ci try

2025-09-09 17:19 UTC, Emilgardis commented
/ci try

seems there was a mirror sync or something happening [x86_64-pc-windows-gnu](https://github.com/cross-rs/cross/actions/runs/17582656360/job/49942876753?pr=1580#)

2025-09-09 18:46 UTC, Emilgardis commented
/ci try -t *pc-windows-gnu

2025-09-28 19:40 UTC, JanDiederich commented on src/lib.rs
> -    clippy::string_to_string,
@Emilgardis Just to clarify this: The mentioned 2025-09-18 has passed, Rust 1.90.0 has been released as planned, and this PR is still work-in-progress, as expected.

2025-11-21 08:29 UTC, Emilgardis commented
/ci try

2025-12-23 11:37 UTC, JanDiederich commented
@Emilgardis What is the last state of this project / branch?

2025-12-23 12:57 UTC, gakonst commented
hi! also wanted to gently follow up here as Ubuntu 24.04 gives us GMP 6.3 vs earlier versions

2025-12-23 16:58 UTC, Emilgardis commented
I want to merge it, the conflicts are easy to fix but the biggest issue is the failing images which should be solved

2026-01-03 19:32 UTC, MichaIng commented
Please do so. Ubuntu 20.04 means that builds are linked against libssl1.1, which is not available natively on any distro younger than 5 years or so.

2026-01-13 16:06 UTC, RedChops commented
I was able to fix the build errors, for at least x86_64-unknown-linux-gnu, by adding `--force-remove-protected` to line 274 of `linux-image.sh`

2026-01-13 17:59 UTC, Emilgardis commented
Hmm, that seems unwise to do

2026-01-13 18:52 UTC, RedChops commented
Given the comment above that line, I think it's required now. That line attempts to remove libgcc_s1:{ARCH} so that we can install for the target arch. I *feel* like previous versions of dpkg were okay removing those packages without the use of that flag, but these new dockerfiles use a much newer version of debian

2026-02-03 08:31 UTC, alexis-opolka commented
Hey ^-^

Just to know, is there still anything blocking this PR that I could help with?

2026-02-03 15:43 UTC, MichaIng commented
The `libgcc-s1` package has indeed the `Protected: yes` set. `--force-remove-protected` has been introduced with `dpkg` 1.20.1, too new for Ubuntu Focal. The `Protected:` field seems to not exist at all before that, so `Priority:` and `Essential:` could have caused such a lock. But `libgcc-s1` has only `Priority: optional` and no `Essential:`, hence `dpkg` was happy to remove it.

Did someone try to skip the package removal? I do not understand the reason: `libgcc-s1:arm64` can be installed in parallel to `libgcc-s1:amd64`, also the latter is installed back again at the end of the script (together with all other removed packages). The libraries are stored to different `/usr/lib/*-linux-gnu/libgcc_s.so.1` paths per arch, and any compiler should pick the correct one based on target arch. But otherwise, the removal is a transitional step only, packages are installed back afterwards. So if it is still needed, `--force-remove-protected` is needed, no reason to worry about it.

2026-02-04 07:51 UTC, Emilgardis commented
I've rebased + squashed the pr but accidentally removed attribution D: i'll fix it :)

2026-02-04 08:14 UTC, Emilgardis commented
/ci try

2026-02-04 09:48 UTC, Emilgardis commented
promising! some new fails but looks like images are building but failing in tests :D

2026-02-04 13:58 UTC, MichaIng commented
Looks like I misinterpreted why the `libgcc-s1` removal was needed: It is not for foreign arch builds, but for native arch builds, where a different version of `libgcc-s1:amd64` is needed for the builds. Now it all makes sense.

Regarding the errors: Either the container images do not contain `/init`, or it/parts of it are for missing or false arch/platform/whatever, so that the kernel fails to execute it:
```
[    2.985256] Run /init as init process
[    2.998782] Failed to execute /init (error -2)
[    2.998956] Run /sbin/init as init process
[    2.999168] Run /etc/init as init process
[    2.999354] Run /bin/init as init process
[    2.999556] Run /bin/sh as init process
[    2.999895] Kernel panic - not syncing: No working init found.
```
Affected are only those images which run `linux-image.sh`, hence only the architectures/ABIs natively supported by `build-docker-image`, excluding musl and such. Since also non-host target archs are affected, the intermediate `libgcc-s1` and `libstdc++6` removal does not seem to be the issue.

```
#20 35.01 + ls -lh /qemu
#20 35.01 total 56M
#20 35.01 -rw-r--r-- 1 root root 20M Feb  4 08:32 initrd.gz
#20 35.01 -rw-r--r-- 1 root root 36M Feb  4 08:32 kernel
```
Is it expected to contain kernel and initramfs images only at the end of `linux-image.sh`?

EDIT: `/init` is created here:
```
#20 27.63 + cat
#20 27.63 + [[ arm64 == \r\i\s\c\v\6\4 ]]
#20 27.63 + chmod +x root-arm64/init
```
Previously, I see we are in `/qemu`:
```
#20 25.44 + cd /qemu
```
`/qemu/root-arm64` is however removed afterwards as "cleanup" step:
```
#20 30.60 + rm -rf /qemu/root-arm64 /qemu/arm64
```
If I am not missing something, this is not intended, is it?

EDIT2: Okay, that `/init` is for and added to the initramfs image, got it.

EDIT3: I tried to find logs from successful builds, but those were all restored from cache, i.e. no output from `linux-image.sh` to compare. And the QEMU machine boot log is only shown if it fails/times out. I am at the end of how much I can reasonably debug here 😅.

2026-02-05 08:01 UTC, Emilgardis commented
/ci try --runners native

lets try without qemu and see the successes

2026-02-05 08:30 UTC, Emilgardis commented
😅ok the ci try command doesn't tell the test framework to use some runners only, oh well...

x86_64-unknown-linux-gnu works without qemu, the others seem broken in building. I'm guessing the qemu issue is what's the problem with the [other images](https://github.com/cross-rs/cross/pull/1580#issuecomment-3846267370) also but it's hard to see with a glance only, should report the failing step in the conclusion comment

2026-02-05 17:03 UTC, MichaIng commented
The target explicitly runs on native runners as well as `qemu-user` and `qemu-system`: https://github.com/cross-rs/cross/blob/main/targets.toml

It seems `--runners native` just filters the targets by those which can run on a native runner, but does not tell it to only run them on native runners. And that seems actually reasonable: While x86 guest can run natively on x86 host, it should also be able to run with QEMU. The reason it fails seems to be the very same why the non-x86 targets fail to boot via `qemu-system`.

Actually, checking again the initramfs which runs [`exec dropbear -F -E -B`](https://github.com/cross-rs/cross/blob/main/docker/linux-image.sh#L389) in the end, i.e. Dropbear with `-F` to stay in foreground. _`-E` is for logging to STDERR and `-B` an undocumented option to allow blank password logins: https://github.com/mkj/dropbear/blob/master/src/svr-runopts.c#L87._ Does this mean it is not supposed to boot beyond the initramfs, hence should not even reach the stage where the kernel looks for `/init`? Seems to, which means the initramfs fails, but we do not see logs of it.

@Emilgardis is it possible to pass `CROSS_DEBUG=1` to via `/ci try`, otherwise maybe hardcode it temporarily for debugging, so we see [QEMU kernel logs from the start](https://github.com/cross-rs/cross/blob/main/docker/linux-runner#L126) instead of only the last 100 lines.

2026-02-05 18:11 UTC, Emilgardis commented
Yes, im working on a way to do CROSS_DEBUG, i thought -v would do it but it doesnt

2026-02-06 12:37 UTC, MichaIng commented on docker/ubuntu.sources
> +Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg
```suggestion
Types: deb
URIs: https://ports.ubuntu.com
Suites: noble noble-updates noble-backports noble-security
Architectures: arm64
Components: main restricted universe multiverse
Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg

Types: deb
URIs: https://archive.ubuntu.com/ubuntu
Suites: noble noble-updates noble-security
Architectures: amd64
Components: main restricted universe multiverse
Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg
```
* `security.ubuntu.com` is just a mirror of `archive.ubuntu.com`. When using the `noble-security` in the latter, it is unnecessary to include the `security.ubuntu.com` repo at all. This only makes sense if you use custom mirrors which might sync only parts of the full Ubuntu repo or have delays, otherwise it just takes more time to `apt update` and takes more space to store the duplicate package lists.
* I believe APT package sources are not needed here, but only the binary packages? It would be needed if one does `apt source <package>` to download the source tarball and compile it manually. Otherwise, adding `deb-src` here similarly just adds to `apt update` processing time and disk usage.
* Use HTTPS. APT should be anyway redirected internally, so this also avoids one unnecessary network request.
* `ports.ubuntu.com/ubuntu-ports` is just a symlink to the root, so `/ubuntu-ports` is not needed:
  - https://ports.ubuntu.com/
  - https://ports.ubuntu.com/ubuntu-ports/
* I believe we want `noble-updates` not only for the target architecture but also for the host architecture. Not sure about `noble-backports`, this is only used when `apt install -t noble-backports <package>` explicitly, or if the package is not available at all in any other repo and suite. This is not the case for the builds at least, and I doubt that it is relevant for the target architecture? Maybe remove it there again (I see it was added explicitly), or do you believe users will need it?
* These images are supposed to run on `x86_64` hosts, so the `i386` architecture shouldn't be needed. Also note that, without adding it here in the list files explicitly, it would not have been downloaded unless `dpkg --add-architecture i386` was done. So adding `i386` here compared to before adds additional processing and disk usage for something that (obviously) was not needed before.
* Similarly, since this file is included for `aarch64` targets only, the `armhf` architecture is not needed, and it would download lists the system does not pick anything from  unless `dpkg --add-architecture armhf` is done.

Related, while I am not sure why the issue this was added for does not happen for the 32-bit ARM and RISC-V targets (or has it just not been tested?), generally it makes sense on cross-target images to limit the architectures APT shall looking for in each repo. So we could replace `arm64` here with `ARCH` or something like that, replace it on build time via `sed` with the actual target DEB architecture, and implement that for all cross target images which Ubuntu (ports) supports, i.e. `armhf`, `arm64`, `riscv64`, `ppc64el`, and `s390x`: https://ports.ubuntu.com/dists/noble/
The `sed` could be also done in `linux-image.sh`:
- For non-native target architectures supported by Ubuntu ports, copy the `ubuntu.sources` in place.
- In `linux-image.sh` `sed -i "s/ARCH/${arch}/" /etc/apt/sources.list.d/ubuntu.sources`, which is a noop if the one with the placeholder "ARCH" was not actually copied.

2026-02-06 17:22 UTC, Emilgardis commented on docker/ubuntu.sources
> +Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg
Thank you for the points, I agree with most of it, and I think using it as a template and `sed`ing it is a good approach and would be necessary for when we support non-x86_64 hosts. The thing I disagree with is dropping deb-src, as I don't think saving unmeasured processing time and disk space is needed, unless it's measured to have a huge impact. I think backports is good to have for forward compatibility.

2026-02-06 18:49 UTC, Emilgardis commented
/ci try --cross-debug

2026-02-06 18:50 UTC, Emilgardis commented
/ci try --cross-debug

:)

2026-02-06 19:20 UTC, MichaIng commented on docker/ubuntu.sources
> +Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg
About the impact of `deb-src` on time and disk usage on a Debian Trixie system:
```console
root@VM-Trixie:~# rm -R /tmp/apt/lists/
root@VM-Trixie:~# time apt update
Get:1 https://deb.debian.org/debian trixie InRelease [140 kB]
Get:2 https://deb.debian.org/debian trixie-updates InRelease [47.3 kB]
Get:3 https://deb.debian.org/debian-security trixie-security InRelease [43.4 kB]
Get:4 https://deb.debian.org/debian trixie-backports InRelease [54.0 kB]
Get:5 https://deb.debian.org/debian trixie/contrib amd64 Packages [53.8 kB]
Get:6 https://deb.debian.org/debian trixie/non-free-firmware amd64 Packages [6884 B]
Get:7 https://deb.debian.org/debian trixie/non-free amd64 Packages [100 kB]
Get:8 https://deb.debian.org/debian trixie/main amd64 Packages [9670 kB]
Get:9 https://deb.debian.org/debian trixie-updates/main amd64 Packages [5412 B]
Get:10 https://deb.debian.org/debian-security trixie-security/main amd64 Packages [100 kB]
Get:11 https://deb.debian.org/debian-security trixie-security/non-free-firmware amd64 Packages [544 B]
Get:12 https://deb.debian.org/debian trixie-backports/non-free-firmware amd64 Packages [4044 B]
Get:13 https://deb.debian.org/debian trixie-backports/main amd64 Packages [146 kB]
Get:14 https://deb.debian.org/debian trixie-backports/non-free amd64 Packages [7352 B]
Get:15 https://deb.debian.org/debian trixie-backports/contrib amd64 Packages [6392 B]
Get:16 https://dietpi.com/apt trixie InRelease [2140 B]
Get:17 https://dietpi.com/apt trixie/main amd64 Packages [4104 B]
Fetched 10.4 MB in 2s (4562 kB/s)
All packages are up to date.

real    0m3.700s
user    0m2.438s
sys     0m1.008s
root@VM-Trixie:~# du -sm /tmp/apt/lists/
57      /tmp/apt/lists/
root@VM-Trixie:~# nano /etc/apt/sources.list
root@VM-Trixie:~# rm -R /tmp/apt/lists/
root@VM-Trixie:~# time apt update
Get:1 https://deb.debian.org/debian trixie InRelease [140 kB]
Get:2 https://deb.debian.org/debian trixie-updates InRelease [47.3 kB]
Get:3 https://deb.debian.org/debian-security trixie-security InRelease [43.4 kB]
Get:4 https://deb.debian.org/debian trixie-backports InRelease [54.0 kB]
Get:5 https://deb.debian.org/debian trixie/contrib Sources [52.3 kB]
Get:6 https://deb.debian.org/debian trixie/main Sources [10.5 MB]
Get:7 https://deb.debian.org/debian trixie/non-free Sources [75.9 kB]
Get:8 https://deb.debian.org/debian trixie/non-free-firmware Sources [6552 B]
Get:9 https://deb.debian.org/debian trixie/contrib amd64 Packages [53.8 kB]
Get:10 https://deb.debian.org/debian trixie/main amd64 Packages [9670 kB]
Get:11 https://dietpi.com/apt trixie InRelease [2140 B]
Get:12 https://dietpi.com/apt trixie/main amd64 Packages [4104 B]
Get:13 https://deb.debian.org/debian trixie/non-free amd64 Packages [100 kB]
Get:14 https://deb.debian.org/debian trixie/non-free-firmware amd64 Packages [6884 B]
Get:15 https://deb.debian.org/debian trixie-updates/main Sources [2788 B]
Get:16 https://deb.debian.org/debian trixie-updates/main amd64 Packages [5412 B]
Get:17 https://deb.debian.org/debian-security trixie-security/main Sources [121 kB]
Get:18 https://deb.debian.org/debian-security trixie-security/non-free-firmware Sources [696 B]
Get:19 https://deb.debian.org/debian-security trixie-security/non-free-firmware amd64 Packages [544 B]
Get:20 https://deb.debian.org/debian-security trixie-security/main amd64 Packages [100 kB]
Get:21 https://deb.debian.org/debian trixie-backports/non-free-firmware Sources [2468 B]
Get:22 https://deb.debian.org/debian trixie-backports/non-free Sources [624 B]
Get:23 https://deb.debian.org/debian trixie-backports/main Sources [137 kB]
Get:24 https://deb.debian.org/debian trixie-backports/contrib Sources [4928 B]
Get:25 https://deb.debian.org/debian trixie-backports/non-free amd64 Packages [7352 B]
Get:26 https://deb.debian.org/debian trixie-backports/contrib amd64 Packages [6392 B]
Get:27 https://deb.debian.org/debian trixie-backports/non-free-firmware amd64 Packages [4044 B]
Get:28 https://deb.debian.org/debian trixie-backports/main amd64 Packages [146 kB]
Fetched 21.3 MB in 4s (5976 kB/s)
All packages are up to date.

real    0m5.650s
user    0m3.631s
sys     0m2.643s
root@VM-Trixie:~# du -sm /tmp/apt/lists/
115     /tmp/apt/lists/
```
So it is roughly doubled amount of data that needs to be downloaded and processed, leading to doubled download time (2s => 4s), and doubled disk usage of the downloaded list files. As said, this is only relevant if one runs `apt source ...` to download source tarballs from the APT repo. Is this often done by users of cross-rs?

> I think backports is good to have for forward compatibility.

For the target arch or the host arch or both? Do users often run `apt install -t *-backports` to install APT packages from the backports suite? As said, this is nothing which happens automatically. But the impact of backports on resources is much smaller, since they do just contain a subset of packages, so it doesn't matter as much as `deb-src`. I want to point at the flexibility vs performance aspect here, while I wonder whether typical cross-rs users ever make use of APT source packages or backports, and if so, not just add the needed repos by themselves. Smaller images which save even just a few seconds however benefit everyone, even if just a little.

2026-02-06 20:07 UTC, MichaIng commented
Nice regarding new `--cross-debug` flag!

So hmm, seeing the full log, actually the failing `/init` seems to be about the one from the initramfs. The `ENOENT` would mean that either `/init` does not exist (but it is definitely created), is not executable (but `chmod +x` is there), or something within the execution chain is missing, like `busybox` from the shebang, or any library it depends on, or it is for the wrong architecture (but native amd64 fails as well).

... do we need `busybox-static`, since `busybox` depends on `libc6`? But `libc6` is explicitly installed/extracted into the root (otherwise almost nothing would work).

2026-02-06 20:09 UTC, Emilgardis commented on docker/ubuntu.sources
> +Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg
Ok, lets drop deb-src, seems useful. As for backports, i was under the impression it was selectable without specifying but seems its the default behaviour to not use them as release. Lets drop it too then 👍

2026-02-06 20:58 UTC, MichaIng commented
I think I got it:
- `libc6` and all other libraries are located below `/usr` now, since usrmerge.
- The default linker most likely looks at `/lib`, or maybe `/lib64`.
- Actually, `readelf -I /usr/bin/busybox` gives `[Requesting program interpreter: /lib64/ld-linux-x86-64.so.2]`.

So what we need is the symlinks for a usrmerged system, just both, or better just all for executables as well:
```sh
ln -sn usr/lib "${root}/lib"
ln -sn usr/lib64 "${root}/lib64"
ln -sn usr/bin "${root}/bin"
ln -sn usr/sbin "${root}/sbin"
```
_Using `-n` dereference flag to assure the symlink is not created within this directory if it exists already. If any of these commands fail, the respective directory exists already, which however should not be the case. But if so, we'd need to create the symlinks before installing/extracting anything else into that `"${root}` path._

2026-02-06 21:27 UTC, Emilgardis commented
nice! that works :D

2026-02-06 21:43 UTC, Emilgardis commented
/ci try --cross-debug

2026-02-06 21:48 UTC, MichaIng commented on docker/linux-image.sh
>      mkdir -p "${root}"/{bin,etc/dropbear,root,sys,dev,proc,sbin,tmp,usr/{bin,sbin},var/log}
```suggestion
    mkdir -p "${root}"/{etc/dropbear,root,sys,dev,proc,tmp,usr/{bin,sbin},var/log}
```
This two should make the `ln` below fail. Maybe its overall more failsafe to create the symlinks first, to assure no package install or so pre-creates the dirs.

2026-02-06 22:06 UTC, MichaIng commented
Further things to fix:
- in [`android-system.sh`](https://github.com/cross-rs/cross/blob/main/docker/android-system.sh): `libncurses5` => `libncurses6`
- [`cmake.sh` run `rm -rf /var/lib/apt/lists/*`](https://github.com/cross-rs/cross/blob/main/docker/cmake.sh#L51C5-L51C32), and some Dockerfile's run `apt-get install` right afterwards, which of course cannot work without lists:
    ```docker
    COPY cmake.sh /
    RUN /cmake.sh
    
    FROM cross-base AS build
    
    RUN apt-get install --assume-yes --no-install-recommends \
        g++-arm-linux-gnueabi \
        gfortran-arm-linux-gnueabi \
        libc6-dev-armel-cross
    ```
    Removing lists is a reasonable cleanup step, but should be probably done at the very end of each Dockerfile/image generation, not as early as `cmake.sh` is sometimes called. No idea how this did not cause failures before this PR, since it is unrelated 🤔. To not potentially break something, of course also an additional `apt-get update` would do.

2026-02-06 22:24 UTC, Emilgardis commented on docker/linux-image.sh
>      mkdir -p "${root}"/{bin,etc/dropbear,root,sys,dev,proc,sbin,tmp,usr/{bin,sbin},var/log}
afaik it should work fine, but it's unnecessary.

2026-02-06 22:38 UTC, MichaIng commented on docker/linux-image.sh
>      mkdir -p "${root}"/{bin,etc/dropbear,root,sys,dev,proc,sbin,tmp,usr/{bin,sbin},var/log}
I know now why it did not fail, but it is not as it was supposed to be, wait.

2026-02-06 22:44 UTC, MichaIng commented on docker/linux-image.sh
> +    done
It did work now, since `/lib` and `/lib64` were linked. But `/bin` and `/sbin` links were put into the previously created `/bin` and `/sbin` directories. I was missing the `-d` flag to assure `ln` takes the actual directory as link target, instead of putting it inside. It did not cause issues here, but if on actual usage or later on something is looking for an executable in `/(s)bin` while all of them are in `/usr/(s)bin`, it might become an issue.

And to prevent any potential package which does not follow usrmerge pre-creates any of the dirs, it is easier to create the symlinks first.
```suggestion

    # make libraries and binaries available as usrmerge
    for d in lib lib64 bin sbin; do
        ln -snd "usr/${d}" "${root}/${d}"
    done
    mkdir -p "${root}"/{etc/dropbear,root,sys,dev,proc,tmp,usr/{bin,sbin,lib,lib64},var/log}
    for deb in "${arch}"/*deb; do
        dpkg -x "${deb}" "${root}"/
    done
```

2026-02-07 22:34 UTC, Emilgardis commented
/ci try

2026-02-07 22:42 UTC, Emilgardis commented on Cargo.toml
> +version = "0.2.6"
this should not be bumped in this pr, and if it should be bumped it should be to 0.3.0, I want to do a alpha + rc first though :)

2026-02-07 23:11 UTC, MichaIng commented on docker/linux-image.sh
> +        debsource="deb http://http.debian.net/debian/ bookworm main"
`http.debian.net` redirects to `deb.debian.org`. And any reason to not use HTTPS here?
```suggestion
        debsource="deb https://deb.debian.org/debian bookworm main"
```
Same for the other sources, but everything below `bullseye` will require `archive.debian.org` instead.

And for `debian-ports` (also available at [`deb.debian.org/debian-ports`](https://deb.debian.org/debian-ports/), a dedicated keyring is needed: https://deb.debian.org/debian-ports/pool/main/d/debian-ports-archive-keyring/

2026-02-07 23:15 UTC, MichaIng commented on docker/linux-image.sh
> +        fi
The directories are expected to not yet exist here, but they will be created with below package installs (or the `mkdir -p` call). Even if they remain non-existent, the symlinks do not hurt. This condition needs to be removed, else, as the test shows, it fails again:
```suggestion
        ln -nsd "usr/${d}" "${root}/${d}"
```

2026-02-07 23:17 UTC, Emilgardis commented on docker/linux-image.sh
> +        fi
Its needed because bookworm/buster/older doesnt have these directories

2026-02-07 23:19 UTC, MichaIng commented on docker/linux-image.sh
> +        fi
Bookworm is as well usr-merged, but right everything below no fully. In that case, below:
```sh
mkdir -p "${root}"/{etc/dropbear,root,sys,dev,proc,tmp,usr/{bin,sbin},var/log}
```
=>
```sh
mkdir -p "${root}"/{etc/dropbear,root,sys,dev,proc,tmp,usr/{bin,sbin,lib,lib64},var/log}
```
If there are any issues with package installs (like "file X is already in package Y"), then it would need to be done conditional based on Debian version. But the symlinks must be all created on Bookworm and Trixie, else things fail.

2026-02-07 23:21 UTC, Emilgardis commented on docker/linux-image.sh
> +        fi
Ah yes, i mixed up the intent and broke what was fixed :D

2026-02-08 22:05 UTC, Emilgardis commented
/ci try

2026-02-08 22:47 UTC, MichaIng commented
Debian ports supports `powerpc` as well: https://deb.debian.org/debian-ports/
Maybe better/easier than using old Jessie from archive?

A bunch of runs failed with 50x and 403 for network requests, most likely due to some rate limiting. It should be possible to rerun only failed jobs directly in the Actions GUI. It does checkout new code for those, only the code of the workflows themselves remains the same. That should speedup test iterations and reduce concurrent network requests to package servers etc.

2026-02-09 00:53 UTC, MichaIng commented on docker/linux-image.sh
```suggestion
```
This is now redundant (and hence fails) with the usr-merge symlinks being created above already.

2026-05-29 19:34 UTC, mcandre commented
Couldn't`su "${username}"` could be simplified to `sh`?

2026-07-01 06:59 UTC, Emilgardis commented
Merged in #1779

2026-07-01 06:59 UTC, closed without merging