Add pre-build hooks
cross-rs/cross pull request #635
Opened 2022-02-07 04:18 UTC by aig787

This PR addresses #565 and hopefully a number of the open issues about the lack of openssl in the builders. It does add a dependency on [gosu](https://github.com/tianon/gosu) which handles lowering the privileges down to user level after the pre-build hooks are run. For now I've only added it to the x86_64-unknown-linux-gnu target for testing pending feedback on it.

I was able to build Cargo successfully with all features with
```toml
[target.x86_64-unknown-linux-gnu]
image = "rustembedded/cross:x86_64-unknown-linux-gnu-0.2.1"
pre-build = """
yum update -y
yum install -y openssl-devel
"""
```

2022-02-07 07:41 UTC, Emilgardis commented
Awesome!

This is really a workaround but it's quite neat.
Why do we need to lower privileges?

2022-02-07 16:22 UTC, aig787 commented
I'm not sure we necessarily need to - just seemed good practice to me especially since when hooks aren't provided the containers are run with the `--user` argument. Lowering privileges was just an attempt at getting us into the same state for the build whether they were provided or not.

2022-03-17 00:38 UTC, otavio requested changes
I just small code comment, but I'd like to say I like the idea, and it does avoid the need for many custom images.

2022-03-17 00:38 UTC, otavio commented on src/docker.rs
> +    };
Please move the code back to the original place as it is a non-required code change.

2022-03-17 16:32 UTC, Emilgardis commented
marking as draft as only one target is implemented right now

2022-03-31 18:09 UTC, aig787 commented
> marking as draft as only one target is implemented right now

I'm happy to get moving on the other targets if we're happy with the implementation. I'm also happy to revert the privilege de escalation first, just need to know what the preference is from your side.

2022-04-01 05:43 UTC, Emilgardis commented
> > marking as draft as only one target is implemented right now
> 
> I'm happy to get moving on the other targets if we're happy with the implementation. I'm also happy to revert the privilege de escalation first, just need to know what the preference is from your side.

I think the gid/uid setting is good, there is a reason we allow setting it.

2022-04-04 15:52 UTC, Emilgardis commented
see my comment on https://github.com/cross-rs/cross/issues/643#issuecomment-1086898664 regarding the "issue" that the image is now centos.

2022-04-05 05:20 UTC, Emilgardis commented
Been thinking about this some more now, would it make sense to actually not do this, and just use the technique in #678 and hook into a dockerfile passed to stdin to `docker build --build-arg cmd=blabla [additional flags] -`

```
FROM {target}
ARG CMD=exit 0
RUN $CMD
```

This way we can even support custom images

2022-05-31 19:16 UTC, patrickelectric commented
This is a great feature!

2022-06-17 15:44 UTC, closed without merging