build images daily, without cache
cross-rs/cross pull request #789
Opened 2022-06-13 21:30 UTC by Emilgardis

2022-06-13 21:31 UTC, Emilgardis commented
this gives me the idea to also start making progress into buildx, it'd be cool if `build-docker-images` had a flag for outputting a bake file

2022-06-13 21:36 UTC, Emilgardis commented on .github/workflows/daily.yml
> +        timeout-minutes: 60
this will probably not work XD

2022-06-14 15:52 UTC, Emilgardis commented
depends on #791

2022-06-14 17:49 UTC, Emilgardis commented
this could also maybe implement parts of #610, checking that mounts works correctly

2022-06-16 18:42 UTC, Alexhuszagh requested changes
Minor nit.

2022-06-16 18:42 UTC, Alexhuszagh commented on .github/workflows/weekly.yml
> +        run: cargo xtask build-docker-image -v --no-cache --from-ci --tag daily
Should be `--tag weekly`.

2022-06-16 18:51 UTC, Emilgardis commented on xtask/src/build_docker_image.rs
> +                })
fixed this too, apparently it went away in some rebase somewhere

2022-06-16 19:30 UTC, Alexhuszagh approved these changes
lgtm

2022-06-16 20:06 UTC, merged